### PR TITLE
Exporter: when no default process is specified, don't set a default process (even when there is only one process)

### LINKED ISSUE #378: Exporter: when no default process is specified, don't set a default process (even when there is only one process)
With platform API 0.4, when no default process is specified and there is exactly one process, the exporter will set the default process (entrypoint) to the only process.

As discussed in WG: the lifecycle should be as transparent as possible and have no opinions. The current behavior could be surprising to some users.

Given: a build with only one process type using platform API 0.4
When: no process type is specified (`-process-type` not passed)
Then: the exporter should set the entrypoint to `/cnb/lifecycle/launcher` (or the Windows equivalent)

### PR DESCRIPTION
**Pull request by natalieparellano**
Fixes #378 

Signed-off-by: Natalie Arellano <narellano@vmware.com>

### CODE REVIEW

**Comment by natalieparellano** [comment]
So it occurred to me to check the spec, and in fact the current behavior is in the spec:

> If <process-type> does not match a buildpack-provided process:
> If there is exactly one buildpack-provided process:
> MUST have ENTRYPOINT=/cnb/process/<type> where <type> matches the type of the process
> Else:
> MUST have ENTRYPOINT set to /cnb/lifecycle/launcher

I believe we should hold off on merging this one.

**Comment by nebhale** [comment]
Concur with the hold.  It’s not critical of 0.9.1 and we might actually want a spec change.

**Comment by natalieparellano** [comment]
I will close this PR (so that we don't accidentally merge it) and we can open another one when we've decided on the implementation strategy.

**Comment by yaelharel** [comment]
@natalieparellano @ekcasey 
Do we want to keep this PR open?
Issue #378 was closed.

**Review by kadirselcuk — APPROVED** [review]

**Comment by natalieparellano** [comment]
Closing, we will do this work as part of https://github.com/buildpacks/lifecycle/issues/457

**Pull request closed without merging**
