### PR TITLE
Refactor launcher to remove dependency on github.com/docker/docker

### PR DESCRIPTION
**Pull request by sclevine**
Addresses #247:
``` 
opal:lifecycle stephen$ du -h out/lifecycle/launcher
2.2M	out/lifecycle/launcher
```

### CODE REVIEW

**Comment by dgageot** [comment]
@sclevine That's awesome!

**Comment by dgageot** [comment]
You might want to check at build time that this binary doesn't grow too much.

**Comment by dgageot** [comment]
@sclevine Do you plan on submitting this PR?

**Comment by sclevine** [comment]
Apologies, @ekcasey and I are working on getting this into the changes in #243, so that both go out in the next release.

**Pull request merged**
