### PR TITLE
Include arm64 artifacts in release

### PR DESCRIPTION
**Pull request by imjasonh**
I've tested this in my fork: https://github.com/imjasonh/lifecycle/releases/tag/v0.0.8

My fork pushed images to ghcr.io instead of Dockerhub: https://github.com/imjasonh/lifecycle/pkgs/container/lifecycle

cc @natalieparellano 

#435

### CODE REVIEW

**Comment by imjasonh** [comment]
@natalieparellano rebased, and verified in my fork: https://github.com/imjasonh/lifecycle/releases/tag/v0.0.15

**Comment by natalieparellano** [comment]
@imjasonh I am sorry to ask you to rebase again, but is it possible you could fix the merge conflicts in draft-release.yml? It should be as simple as updating the guards [here](https://github.com/buildpacks/lifecycle/blob/90a36d1eb261fb23ea564b06eefb5e50904107d8/.github/workflows/draft-release.yml#L75) and [here](https://github.com/buildpacks/lifecycle/blob/90a36d1eb261fb23ea564b06eefb5e50904107d8/.github/workflows/draft-release.yml#L83) - I think the other changes could be discarded since the arm artifacts will get pulled in automatically if they start with `lifecycle-`.

**Comment by natalieparellano** [comment]
@imjasonh I took the liberty of resolving the conflicts so that we could move forward with the release (that includes the arm binaries!). I hope it's okay!

**Comment by imjasonh** [comment]
> @imjasonh I took the liberty of resolving the conflicts so that we could move forward with the release (that includes the arm binaries!). I hope it's okay!

No worries! I'm actually out of the office for another week or so, so do whatever you have to do. If there's anything left when I get back I'm happy to do it. 😄

**Comment by natalieparellano** [comment]
Tested on fork: https://github.com/natalieparellano/lifecycle/releases/tag/v0.901.0

On an arm machine:
```
# docker run natalieparellano/lifecycle:0.901.0-linux-arm64 /cnb/lifecycle/lifecycle -version
0.901.0+e2522ec4
```

**Review by natalieparellano — APPROVED** [review]

**Review by jabrown85 — APPROVED** [review]

**Pull request merged**
